### ISSUE TITLE
Issue with cg_level

### ISSUE THREAD

**Issue by sssongrm** [kyonofx/mlcgmd#3]
I changed the value of cg_level in the graphwm/conf/model/chain.yaml, cg_level: 1
An error is reported after running the train.py: 
AttributeError: Error instantiating 'graphwm.model.gns.GNS' : Missing attribute "use_keypoint_for_cg"

How should I run the cg_level=1 situation?

**Comment by kyonofx** [comment]
Thank you for the question, this should be fixed by this 1-line modification:

https://github.com/kyonofx/mlcgmd/commit/3798b6ac86622ef106be873d77def1aed13e8bf6

**Comment by sssongrm** [comment]
***@***.******@***.***

**Comment by sssongrm** [comment]
There are new errors after modifying the code:
  File "/mlcgmd-main/graphwm/model/gns.py", line 76, in forward
    prop_pred = self.predict_prop(latent_graph, pos_seq[:, -1], weights, n_cg_node)
  File "/mlcgmd-main/graphwm/model/base.py", line 215, in predict_prop
    pred = pred + utils.compute_weighted_rgs(pos.detach(), weights.detach(), n_node)
  File "/mlcgmd-main/graphwm/model/utils.py", line 86, in compute_weighted_rgs
    com = (positions * weights).sum(0) / weights.sum()
RuntimeError: The size of tensor a (3) must match the size of tensor b (500) at non-singleton dimension 1

What should I do? And what is use_keypoint_for_cg used for? I did not find a definition of it in the project.

**Comment by kyonofx** [comment]
how about now? with this 1-line change:

https://github.com/kyonofx/mlcgmd/commit/b8879aa98977cff083a72917ac4c730afdd0a5a2

if `use_keypoint_for_cg` is `True` the cluster keypoint node position instead of the CoM of a node cluster is used for the position of the CG bead. It is something I tried during development and can be safely ignored.
