### ISSUE TITLE
Empty `protein_to_h5` function significance

### ISSUE THREAD

**Issue by patriksimurka** [kyonofx/mlcgmd#5]
Hi,

I've noticed there's this `protein_to_h5` function and since I'm playing around with the code and considering adapting it to proteins, I was wondering why the function was left empty.

I believe any inputs could prove very valuable to me.

Many thanks!

**Comment by kyonofx** [comment]
Hi,

Thanks for your interest. I have tried some protein data (DESRES fast folding proteins) during development but the results were not good enough so I did not include them in the paper. The main challenges were limited data (different trajectories were sampled with different setups) and extremely long-time-scale folding events (only happens a handful of times over the ms-level trajectories).

**Comment by patriksimurka** [comment]
Thanks for the timely answer!

Have you also tried with both corse-graining on and off? If so, what difference did it make?

Thanks a lot

**Comment by kyonofx** [comment]
I only tried CG with Calpha as CG-bead coordinates. The model can recover a decent contact map and folding/unfolding can be observed, but the time scale for the folding events is off.

**Comment by kyonofx** [comment]
Feel free to reopen if there are further questions.
