### ISSUE TITLE
difficulty for obtaining the solid polymer electrolyte dataset

### ISSUE THREAD

**Issue by JHL-452b** [kyonofx/mlcgmd#6]
The solid polymer electrolyte dataset [link](https://arxiv.org/abs/2208.01692) provided in the code is arXiv of a paper. If I understand correctly, the data set should be in the supplementary or code link of this paper. But it's hard for me to choose right data without more information. Could you please give me more accurate data-source link?

**Comment by kyonofx** [comment]
Hi, that paper contains the link to the data https://www.htpmd.matr.io/. The trajectory IDs used in this paper are here https://github.com/kyonofx/mlcgmd/tree/main/graphwm/splits/battery. You can also contact the corresponding authors for questions regarding downloading the trajectory data.

**Comment by kyonofx** [comment]
feel free to reopen if you have further question.
