### ISSUE TITLE
Issue with graphwm/preprocess

### ISSUE THREAD

**Issue by sssongrm** [kyonofx/mlcgmd#7]
May I ask where I can download the `coords.lammpstrj` and `poly-0.pdb` mentioned in function `load_polymer_rg` of file `graphwm/preprocess/chain.py`?

**Comment by kyonofx** [comment]
Thanks for your question. I no longer have possession of the raw files as my collaborator has left MIT. You can find the preprocessed files here: https://zenodo.org/records/6764836. I am also attaching an example LAMMPS setup of the original simulations, hope this helps.

[rand001.tar.gz](https://github.com/kyonofx/mlcgmd/files/13850942/rand001.tar.gz)

**Comment by sssongrm** [comment]
***@***.******@***.***
